name: eco_heroes
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bonfire: ^3.10.2
  flame: ^1.18.0
  collection: ^1.16.0
  flame_audio: ^2.10.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true # includes Material Icons font

  assets:
    - assets/images/eco-heroes.tmj
    - assets/images/spr_tileset_sunnysideworld_16px.png
    - assets/images/player/knight_run.png
    - assets/images/player/knight_idle.png
    - assets/images/player/eco_hero_idle.png
    - assets/images/player/eco_hero_run_down.png
    - assets/images/player/eco_hero_run_up.png
    - assets/images/player/eco_hero_run_left.png
    - assets/images/player/eco_hero_run_right.png

    - assets/images/trash.png
    - assets/images/squirrel.png
    - assets/images/player/player_idle_right.png
    - assets/images/recycling_minigame_background.jpg
  
    - assets/images/cut_scenes/dirty-city.jpg
    - assets/images/cut_scenes/clean-city.jpg

    - assets/images/maps/trash_picking/ParkArea.tmj
    - assets/images/maps/trash_picking/tileset.png
    - assets/images/maps/trash_picking/OutdoorCamping.gif
    - assets/images/maps/trash_picking/City Prop Tileset update 2.png


    - assets/images/maps/chopped_down_forrest/choppedDownForrest.tmj
    - assets/images/maps/chopped_down_forrest/Forest ground.png
    - assets/images/maps/chopped_down_forrest/Forest props.png
    - assets/images/maps/chopped_down_forrest/OutdoorCamping.gif
    - assets/images/maps/chopped_down_forrest/zeo254-completed-commission.png
    - assets/images/maps/chopped_down_forrest/tileset.png
    - assets/images/planted_tree.png

    - assets/images/bins.png
    - assets/images/trash_objects/egg.png
    - assets/images/trash_objects/banana.png
    - assets/images/trash_objects/plastic_bag.png
    - assets/images/trash_objects/milk.png
    - assets/images/trash_objects/magazine.png
    - assets/images/trash_objects/box.png
    - assets/images/trash_objects/apple.png
    - assets/images/trash_objects/cup.png

    - assets/images/maps/apartment/apartment.tmj
    - assets/images/maps/apartment/1024-1092.jpg
    - assets/images/lamps/floor-lamp.png
    - assets/images/lamps/table-lamp.png

    - assets/audio/birds.wav
    - assets/audio/city.wav
    - assets/audio/minigame_success.wav
    - assets/audio/rain.wav
    - assets/audio/success.wav
    - assets/audio/walking.wav
    - assets/audio/wrong.mp3
    - assets/audio/loop_music.wav
    - assets/audio/switch.wav
